import { Template } from '../types/layoutConfig';

export const templateRegistry: Template[] = [
  {
    id: 'romantic-blush',
    name: 'Romantic Blush',
    description: 'Soft, romantic design with rose and pink tones perfect for traditional love stories',
    defaultThemePreset: {
      primary: '#f43f5e',
      secondary: '#fb7185',
      accent: '#fda4af',
      background: '#fff1f2',
      text: '#1f2937',
      fontFamily: 'Georgia, serif',
      fontHeading: 'Playfair Display, serif',
    },
    defaultLayout: {
      sections: [
        { type: 'hero', variant: 'classic', enabled: true, bindings: { bride: 'Emily', groom: 'James', date: 'June 15, 2025', location: 'Garden Estate' } },
        { type: 'story', variant: 'classic', enabled: true },
        { type: 'venue', variant: 'classic', enabled: true },
        { type: 'schedule', variant: 'classic', enabled: true },
        { type: 'gallery', variant: 'classic', enabled: true },
        { type: 'travel', variant: 'classic', enabled: true },
        { type: 'registry', variant: 'classic', enabled: true },
        { type: 'rsvp', variant: 'classic', enabled: true },
        { type: 'faq', variant: 'classic', enabled: true },
        { type: 'footer', variant: 'classic', enabled: true },
      ],
    },
  },
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    description: 'Ultra-clean minimalist aesthetic with crisp typography and maximum whitespace',
    defaultThemePreset: {
      primary: '#000000',
      secondary: '#6b7280',
      accent: '#d1d5db',
      background: '#ffffff',
      text: '#111827',
      fontFamily: 'Inter, sans-serif',
      fontHeading: 'Helvetica Neue, sans-serif',
    },
    defaultLayout: {
      sections: [
        { type: 'hero', variant: 'minimal', enabled: true, bindings: { bride: 'Sophia', groom: 'Alexander', date: '08.20.2025' } },
        { type: 'venue', variant: 'minimal', enabled: true },
        { type: 'story', variant: 'classic', enabled: true },
        { type: 'gallery', variant: 'classic', enabled: true },
        { type: 'rsvp', variant: 'classic', enabled: true },
        { type: 'footer', variant: 'classic', enabled: true },
      ],
    },
  },
  {
    id: 'editorial-bold',
    name: 'Editorial Bold',
    description: 'Magazine-inspired design with dramatic black backgrounds and bold typography',
    defaultThemePreset: {
      primary: '#ffffff',
      secondary: '#f3f4f6',
      accent: '#9ca3af',
      background: '#000000',
      text: '#ffffff',
      fontFamily: 'Helvetica, sans-serif',
      fontHeading: 'Futura, sans-serif',
    },
    defaultLayout: {
      sections: [
        { type: 'hero', variant: 'editorial', enabled: true, bindings: { bride: 'Isabella', groom: 'Sebastian', date: 'September 12, 2025' } },
        { type: 'story', variant: 'timeline', enabled: true },
        { type: 'gallery', variant: 'masonry', enabled: true },
        { type: 'venue', variant: 'classic', enabled: true },
        { type: 'rsvp', variant: 'classic', enabled: true },
        { type: 'footer', variant: 'classic', enabled: true },
      ],
    },
  },
  {
    id: 'luxury-blacktie',
    name: 'Luxury Black Tie',
    description: 'Opulent design with rich blacks, golds, and sophisticated elegance for formal affairs',
    defaultThemePreset: {
      primary: '#f59e0b',
      secondary: '#d97706',
      accent: '#fbbf24',
      background: '#0f172a',
      text: '#f1f5f9',
      fontFamily: 'Cormorant Garamond, serif',
      fontHeading: 'Cinzel, serif',
    },
    defaultLayout: {
      sections: [
        { type: 'hero', variant: 'luxury', enabled: true, bindings: { bride: 'Victoria', groom: 'William', date: 'December 31, 2025', venue: 'Grand Ballroom' } },
        { type: 'countdown', variant: 'classic', enabled: true },
        { type: 'story', variant: 'classic', enabled: true },
        { type: 'venue', variant: 'classic', enabled: true },
        { type: 'schedule', variant: 'classic', enabled: true },
        { type: 'gallery', variant: 'classic', enabled: true },
        { type: 'travel', variant: 'classic', enabled: true },
        { type: 'registry', variant: 'classic', enabled: true },
        { type: 'rsvp', variant: 'classic', enabled: true },
        { type: 'faq', variant: 'classic', enabled: true },
        { type: 'footer', variant: 'classic', enabled: true },
      ],
    },
  },
  {
    id: 'garden-fresh',
    name: 'Garden Fresh',
    description: 'Botanical-inspired with lush greens and natural textures for outdoor celebrations',
    defaultThemePreset: {
      primary: '#059669',
      secondary: '#10b981',
      accent: '#34d399',
      background: '#ecfdf5',
      text: '#064e3b',
      fontFamily: 'Lora, serif',
      fontHeading: 'Spectral, serif',
    },
    defaultLayout: {
      sections: [
        { type: 'hero', variant: 'garden', enabled: true, bindings: { bride: 'Lily', groom: 'Oliver', date: 'May 22, 2025' } },
        { type: 'story', variant: 'classic', enabled: true },
        { type: 'venue', variant: 'classic', enabled: true },
        { type: 'gallery', variant: 'classic', enabled: true },
        { type: 'schedule', variant: 'classic', enabled: true },
        { type: 'travel', variant: 'classic', enabled: true },
        { type: 'rsvp', variant: 'classic', enabled: true },
        { type: 'faq', variant: 'classic', enabled: true },
        { type: 'footer', variant: 'classic', enabled: true },
      ],
    },
  },
  {
    id: 'coastal-breeze',
    name: 'Coastal Breeze',
    description: 'Beach-inspired with ocean blues and sandy neutrals for seaside weddings',
    defaultThemePreset: {
      primary: '#0ea5e9',
      secondary: '#38bdf8',
      accent: '#7dd3fc',
      background: '#f0f9ff',
      text: '#0c4a6e',
      fontFamily: 'Merriweather, serif',
      fontHeading: 'Montserrat, sans-serif',
    },
    defaultLayout: {
      sections: [
        { type: 'hero', variant: 'coastal', enabled: true, bindings: { bride: 'Marina', groom: 'Kai', date: 'July 8, 2025' } },
        { type: 'story', variant: 'timeline', enabled: true },
        { type: 'venue', variant: 'classic', enabled: true },
        { type: 'gallery', variant: 'classic', enabled: true },
        { type: 'travel', variant: 'classic', enabled: true },
        { type: 'schedule', variant: 'classic', enabled: true },
        { type: 'rsvp', variant: 'classic', enabled: true },
        { type: 'footer', variant: 'classic', enabled: true },
      ],
    },
  },
  {
    id: 'rustic-chic',
    name: 'Rustic Chic',
    description: 'Warm, earthy tones with vintage charm for barn and countryside venues',
    defaultThemePreset: {
      primary: '#92400e',
      secondary: '#b45309',
      accent: '#d97706',
      background: '#fef3c7',
      text: '#451a03',
      fontFamily: 'Crimson Text, serif',
      fontHeading: 'Josefin Sans, sans-serif',
    },
    defaultLayout: {
      sections: [
        { type: 'hero', variant: 'classic', enabled: true, bindings: { bride: 'Hannah', groom: 'Jacob', date: 'October 5, 2025', location: 'Willow Creek Barn' } },
        { type: 'story', variant: 'classic', enabled: true },
        { type: 'venue', variant: 'classic', enabled: true },
        { type: 'schedule', variant: 'classic', enabled: true },
        { type: 'gallery', variant: 'classic', enabled: true },
        { type: 'registry', variant: 'classic', enabled: true },
        { type: 'rsvp', variant: 'classic', enabled: true },
        { type: 'faq', variant: 'classic', enabled: true },
        { type: 'footer', variant: 'classic', enabled: true },
      ],
    },
  },
  {
    id: 'playful-colorful',
    name: 'Playful Colorful',
    description: 'Vibrant, joyful design with bold colors and fun animations for modern couples',
    defaultThemePreset: {
      primary: '#d946ef',
      secondary: '#ec4899',
      accent: '#fbbf24',
      background: '#fef3c7',
      text: '#831843',
      fontFamily: 'Nunito, sans-serif',
      fontHeading: 'Poppins, sans-serif',
    },
    defaultLayout: {
      sections: [
        { type: 'hero', variant: 'playful', enabled: true, bindings: { bride: 'Mia', groom: 'Leo', date: 'June 15, 2025' } },
        { type: 'countdown', variant: 'classic', enabled: true },
        { type: 'story', variant: 'timeline', enabled: true },
        { type: 'gallery', variant: 'classic', enabled: true },
        { type: 'venue', variant: 'classic', enabled: true },
        { type: 'schedule', variant: 'classic', enabled: true },
        { type: 'rsvp', variant: 'classic', enabled: true },
        { type: 'footer', variant: 'classic', enabled: true },
      ],
    },
  },
  {
    id: 'classic-timeless',
    name: 'Classic Timeless',
    description: 'Traditional elegance that never goes out of style with refined details',
    defaultThemePreset: {
      primary: '#4b5563',
      secondary: '#6b7280',
      accent: '#9ca3af',
      background: '#f9fafb',
      text: '#111827',
      fontFamily: 'Garamond, serif',
      fontHeading: 'Baskerville, serif',
    },
    defaultLayout: {
      sections: [
        { type: 'hero', variant: 'classic', enabled: true, bindings: { bride: 'Elizabeth', groom: 'Charles', date: 'November 20, 2025', location: 'Heritage Chapel' } },
        { type: 'story', variant: 'classic', enabled: true },
        { type: 'venue', variant: 'classic', enabled: true },
        { type: 'schedule', variant: 'classic', enabled: true },
        { type: 'gallery', variant: 'classic', enabled: true },
        { type: 'travel', variant: 'classic', enabled: true },
        { type: 'registry', variant: 'classic', enabled: true },
        { type: 'rsvp', variant: 'classic', enabled: true },
        { type: 'faq', variant: 'classic', enabled: true },
        { type: 'footer', variant: 'classic', enabled: true },
      ],
    },
  },
  {
    id: 'moody-cinematic',
    name: 'Moody Cinematic',
    description: 'Dark, dramatic atmosphere with film-inspired aesthetics and rich purples',
    defaultThemePreset: {
      primary: '#a855f7',
      secondary: '#9333ea',
      accent: '#c084fc',
      background: '#18181b',
      text: '#fafafa',
      fontFamily: 'Libre Baskerville, serif',
      fontHeading: 'Bebas Neue, sans-serif',
    },
    defaultLayout: {
      sections: [
        { type: 'hero', variant: 'moody', enabled: true, bindings: { bride: 'Raven', groom: 'Dante', date: 'October 31, 2025' } },
        { type: 'story', variant: 'timeline', enabled: true },
        { type: 'gallery', variant: 'masonry', enabled: true },
        { type: 'venue', variant: 'classic', enabled: true },
        { type: 'schedule', variant: 'classic', enabled: true },
        { type: 'rsvp', variant: 'classic', enabled: true },
        { type: 'footer', variant: 'classic', enabled: true },
      ],
    },
  },
  {
    id: 'destination-travel',
    name: 'Destination Adventure',
    description: 'Travel-forward design emphasizing the journey and exotic location details',
    defaultThemePreset: {
      primary: '#0891b2',
      secondary: '#06b6d4',
      accent: '#22d3ee',
      background: '#ecfeff',
      text: '#164e63',
      fontFamily: 'Open Sans, sans-serif',
      fontHeading: 'Raleway, sans-serif',
    },
    defaultLayout: {
      sections: [
        { type: 'hero', variant: 'coastal', enabled: true, bindings: { bride: 'Aria', groom: 'Marco', date: 'April 10, 2025', location: 'Santorini, Greece' } },
        { type: 'story', variant: 'classic', enabled: true },
        { type: 'venue', variant: 'classic', enabled: true },
        { type: 'travel', variant: 'classic', enabled: true },
        { type: 'schedule', variant: 'classic', enabled: true },
        { type: 'gallery', variant: 'classic', enabled: true },
        { type: 'rsvp', variant: 'classic', enabled: true },
        { type: 'faq', variant: 'classic', enabled: true },
        { type: 'footer', variant: 'classic', enabled: true },
      ],
    },
  },
  {
    id: 'photo-storytelling',
    name: 'Photo Storytelling',
    description: 'Image-driven narrative with large galleries showcasing your love story visually',
    defaultThemePreset: {
      primary: '#374151',
      secondary: '#4b5563',
      accent: '#6b7280',
      background: '#111827',
      text: '#f9fafb',
      fontFamily: 'Source Sans Pro, sans-serif',
      fontHeading: 'Oswald, sans-serif',
    },
    defaultLayout: {
      sections: [
        { type: 'hero', variant: 'editorial', enabled: true, bindings: { bride: 'Nina', groom: 'Alex', date: 'August 15, 2025' } },
        { type: 'gallery', variant: 'masonry', enabled: true },
        { type: 'story', variant: 'timeline', enabled: true },
        { type: 'gallery', variant: 'classic', enabled: true },
        { type: 'venue', variant: 'classic', enabled: true },
        { type: 'rsvp', variant: 'classic', enabled: true },
        { type: 'footer', variant: 'classic', enabled: true },
      ],
    },
  },
];

export function getTemplateById(id: string): Template | undefined {
  return templateRegistry.find(template => template.id === id);
}

export function getAllTemplates(): Template[] {
  return templateRegistry;
}
